# Generated by Django 2.2.24 on 2022-03-16 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='Dni')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('data_created', models.DateTimeField(auto_now=True)),
                ('data_updated', models.DateTimeField(auto_now_add=True)),
                ('age', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('State', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%M/%D')),
                ('cvc', models.FileField(blank=True, null=True, upload_to='cvc/%Y/%M/%D')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['id'],
            },
        ),
    ]
